python train_vae2d.py \
    --save_path="./snapshots/JHTDB/inst_norm_2d" \
    --batch_size=32 \
    --iterations=400 \
    --model_dim=16 \
    --input_size=256 \
    --n_frame="1" \
    --lr=0.0005 \
    --beta_start=0.5 \
    --train_set="JHTDB" \
    --test_set="JHTDB" \
    --init_beta=0.00001 \
    --end_beta=0.00002