E3SM:
  data_path: /blue/ranka/xiao.li/dataset/climate_dataset/dataset_numpy/08.npz
  inst_norm: false
  size: 240
  t_step: 1
  test_norm: range
  test_size: 128
  test_var:
  - 0
  train_norm: range
  train_var:
  - 1
  - 2
  - 3
  - 4
Hurricane:
  all_vars:
  - pressure
  - temperature
  data_path: /home/xiao.li/SciDatasets/Hurricane/data
  inst_norm: true
  size: 500
  t_step: 1
  test_norm: range
  test_size: 256
  test_var:
  - pressure
  train_aug: &id001
    downsample: 2
  train_norm: range
  train_var:
  - pressure
  - temperature
JHTDB:
  all_vars:
  - Pressure_0001
  - xcoor
  - ycoor
  - zcoor
  data_path: /home/xiao.li/SciDatasets/JHTDB/channel_psl.h5
  inst_norm: true
  size: 512
  t_step: 1
  test_norm: range
  test_size: 256
  test_var:
  - Pressure_0001
  train_aug: *id001
  train_norm: range
  train_var:
  - Pressure_0001
NYX:
  all_vars:
  - baryon_density
  - dark_matter_density
  - temperature
  - velocity_x
  - velocity_y
  - velocity_z
  data_path: /home/xiao.li/SciDatasets/NYX/Nyx/NVB_C009_l10n512_S12345T692_z42.hdf5
  inst_norm: true
  size: 512
  t_step: 1
  test_norm: range
  test_size: 512
  test_var:
  - dark_matter_density
  train_aug: *id001
  train_norm: range
  train_var:
  - baryon_density
  - temperature
S3D:
  data_path: /home/xiao.li/ClimateModeling/shared_fdmodel/s3d/dataset/S3D/1.dataSet/nHep58/input_150to200steps.npy
  inst_norm: true
  size: 640
  t_step: 1
  test_norm: range
  test_size: 640
  test_var:
  - 40
  - 41
  - 42
  - 43
  - 44
  - 45
  - 46
  - 47
  - 48
  - 49
  - 50
  - 51
  - 52
  - 53
  - 54
  - 55
  - 56
  - 57
  total_frame: 48
  train_aug: *id001
  train_norm: range
  train_var:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  - 19
  - 20
  - 21
  - 22
  - 23
  - 24
  - 25
  - 26
  - 27
  - 28
  - 29
  - 30
  - 31
  - 32
  - 33
  - 34
  - 35
  - 36
  - 37
  - 38
  - 39
Video:
  all_vars:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  data_path: /home/xiao.li/SciDatasets/Video/vimeo_septuplet/output_interp2frame/
  inst_norm: true
  size: 448
  t_step: 1
  test_norm: range
  test_size: 256
  test_var:
  - 0
  train_aug: {}
  train_norm: range
  train_var:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  - 19
