E3SM:
  data_path: /blue/ranka/shared-xiaoli/ScientificDataset/E3SM/e3sm.npz
  test_subset:
    frame_range:
    - 5760
    - 6480
    section_range:
    - 0
    - 6
    variable_idx:
    - 0
  train_subset:
    frame_range:
    - 0
    - 5760
    section_range:
    - 0
    - 6
    variable_idx:
    - 0
    - 1
    - 2
    - 3
    - 4
ERA5:
  data_path: /blue/ranka/shared-xiaoli/ScientificDataset/ERA5/era5.npz
  test_subset:
    frame_range: null
    section_range: null
    variable_idx: null
  train_subset:
    frame_range: null
    section_range: null
    variable_idx: null
Hurricane:
  data_path: /blue/ranka/shared-xiaoli/ScientificDataset/Hurricane/hurricane.npz
  test_subset:
    frame_range: null
    section_range: null
    variable_idx: null
  train_subset:
    frame_range: null
    section_range: null
    variable_idx: null
JHTDB:
  data_path: /blue/ranka/shared-xiaoli/ScientificDataset/JHTDB/jhtdb.npz
  test_subset:
    frame_range:
    - 0
    - 128
    section_range:
    - 0
    - 64
    variable_idx:
    - 0
    - 1
    - 2
  train_subset:
    frame_range:
    - 0
    - 128
    section_range:
    - 0
    - 64
    variable_idx:
    - 0
    - 1
    - 2
PDE:
  data_path: /blue/ranka/shared-xiaoli/ScientificDataset/PDE/pde.npz
  test_subset:
    frame_range: null
    section_range: null
    variable_idx: null
  train_subset:
    frame_range: null
    section_range: null
    variable_idx: null
S3D:
  data_path: /blue/ranka/shared-xiaoli/ScientificDataset/S3D/s3d.npz
  test_subset:
    frame_range:
    - 0
    - 50
    section_range:
    - 0
    - 1
    variable_idx:
    - 8
  train_subset:
    frame_range:
    - 0
    - 50
    section_range:
    - 0
    - 1
    variable_idx:
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
    - 27
    - 28
    - 29
    - 30
    - 31
    - 32
    - 33
    - 34
    - 35
    - 36
    - 37
    - 38
    - 39
    - 40
    - 41
    - 42
    - 43
    - 44
    - 45
    - 46
    - 47
    - 48
    - 49
    - 50
    - 51
    - 52
    - 53
    - 54
    - 55
    - 56
    - 57
test_config:
  augment_type: {}
  inst_norm: false
  n_frame: 1
  n_overlap: 0
  norm_type: mean_range_hw
  train: false
train_config:
  augment_type: {}
  inst_norm: true
  n_frame: 1
  n_overlap: 0
  norm_type: mean_range_hw
  train: true
